### ISSUE TITLE
Import error with newest versions of SpikingJelly + error in git repo homepage

### ISSUE THREAD

**Issue by NicolaCST** [iCGY96/syops-counter#3]
Hi all,
i was trying to install this library and import the module named "get_model_complexity_info". However it is not possible since it requires the old 'spikingjelly.clock_driven', while the newest version uses '.activation_based'.

I've cloned the repo in Colab and changed the module name to .activation_based and removed all the references to old neuros like "MultiStepLIF". It Works

----------------

I think that there is a small error in the landing page of this repo

```python
    ops, params = get_model_complexity_info(net, (3, 224, 224), dataloader, as_strings=True,
                                            print_per_layer_stat=True, verbose=True)
    print('{:<30}  {:<8}'.format('Computational complexity ACs:', acs))
    print('{:<30}  {:<8}'.format('Computational complexity MACs:', macs))
    print('{:<30}  {:<8}'.format('Number of parameters: ', params))
```

There are no references to 'acs' and 'macs', but by checking the returns of the function, i assume that they should be something similar to 'ops[1]' and 'ops[2]'

**Comment by gary23ai** [comment]
Thank you for the reminder. We have included a description for Spikingjelly in version 0.0.4 and will also update the latest version of Spikingjelly’s API.
