### ISSUE TITLE
关于EC(mJ)计算的一些疑问

### ISSUE THREAD

**Issue by ZHENG2049** [iCGY96/syops-counter#5]
您好，我在看您的论文时您论文中给出了几种模型的Estimated Consumption (EC)和Dynamic Consumption (DC)，根据您论文中的描述，
Estimated Consumption (EC)似乎是由公式（15）计算得出的。
$$\mathrm E(\mathcal F)\in[T\cdot E_{m a c}\cdot O_{m a c},T\cdot(E_{a c}\cdot O_{a c}+E_{m a c}\cdot O_{m a c})] \quad(15)$$  
您论文中的结果如下：
![image](https://github.com/iCGY96/syops-counter/assets/93104689/0c61f0a7-b1d2-4730-bf73-45975764bb41)

以Spiking ResNet-34为例， $O_{ac}(G),O_{mac}(G)$  分别为5.34，0.15，T=6。在45nm工艺中 $E_{MAC}$  和 $E_{AC}$  分别为 4.6pJ ，0.9pJ。
我讲这些数据带入公式（15）并未得到您论文中的结果：  $EC(mJ) \in [0.69, 19.85]$    
请问是否是我的理解有误？

**Comment by gary23ai** [comment]
您好，这里的 $O_{ac}(G),O_{mac}(G)$ 分别为DC中的 $O_{ac}(G),O_{mac}(G)$ ，即考虑了步长T和脉冲发放率。所以由此 $O_{ac}(G),O_{mac}(G)$ 推断出的EC只能推断其最小值为0.15*4.6=0.69，最大值需要根据全脉冲条件下计算全部 $O_{ac}(G)$ 获得。

感谢您提出的问题，我们将在论文表头中进行细致的说明。

**Comment by zzzkdata** [comment]
如果使用需要计算模型的DC，使用您提供的示例代码计算模型在一定步长下的 $O_{ac}$ 和 $O_{mac}$ ,以及平均脉冲发放率，
将其带入公式（7） $E(\mathcal F)=T\cdot(fr\cdot E_{ac}\cdot O_{ac}+E_{mac}\cdot O_{mac}).$  是否可行？
计算EC范围的话，根据您的回答需要计算全脉冲条件下的全部 $O_{ac}$ ，该如何在您给出的示例代码的基础上进行修改呢？

**Comment by ZHENG2049** [comment]
非常感谢您的回答，我还有一些疑问。
计算模型的DC的话，根据您论文中的公式(7) $E(\mathcal F)=T\cdot(fr\cdot E_{ac}\cdot O_{ac}+E_{mac}\cdot O_{mac})$ ,使用您提供的示例代码，计算模型在一定步长下的 $O_{ac},O_{mac}$ 以及脉冲平均发放率，将其带入公式(7),是否可行？
但是如何在您示例代码的基础上修改，实现计算全脉冲条件下全部 $O_{ac}$,用于计算EC范围呢？

**Comment by gary23ai** [comment]
计算模型在一定步长下的 $O_{ac},O_{mac}$ 以及脉冲平均发放率，将其带入公式(7)是可行的。但需要更改每个脉冲算子的输入和输出，保证输出全为脉冲或全为0，会稍微复杂一些。一种可行的方法是更改所有Ops的输入和输出，但工作量会稍微大一些。

**Comment by ZHENG2049** [comment]
非常感谢您的解答

**Comment by ZHENG2049** [comment]
@iCGY96 您好，我在计算SNN模型动态功耗时，根据您的计算方法，并没有得出SNN模型更加energy-efficient的结论。
主要原因是SNN中的  $O_{mac}$  明显大于ANN，我是使用spikingjelly搭建的模型，我看您的benchmark种sew_resnet与resnet也出现了同样的结果。

Model | Input Resolution | Params(M) | ACs(G) | MACs(G) | Energy (mJ) | Acc@1 | Acc@5
-- | -- | -- | -- | -- | -- | -- | --
sew_resnet18 | 224x224 | 11.69 | 0.50 | 2.75 | 13.10 | 63.18 | 84.53
resnet18 | 224x224 | 11.69 | 0.00 | 1.82 | 8.372 | 69.76 | 89.08

如果按照您论文中的方法来计算的话 $E(\mathcal F)=T\cdot(fr\cdot E_{ac}\cdot O_{ac}+E_{mac}\cdot O_{mac})$ .由于SNN得到的 
  $O_{mac}$  较大，如何时间步长又比较长的话（T>10）,这应该难以得出SNN更加energy-efficient结论。
请问是什么原因造成的呢？有什么解决方法吗？

**Comment by gary23ai** [comment]
这和具体硬件有关，有些类脑芯片可以实现更低的功耗性能，这里只是基于某一芯片的累加和加乘的功耗进行对比。
